apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-todo-add-tasks-api

spec:
  replicas: {{ .Values.addTask.replicas }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-add-tasks-api

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-todo-add-tasks-api
        azure.workload.identity/use: "true"

    spec:
      serviceAccountName: todoapp-sa

      containers:
        - name: {{ .Release.Name }}-todo-add-tasks-api
          image: "{{ .Values.common.containerRegistryURL }}/{{ .Values.addTask.image.name }}:{{ .Values.addTask.image.tag }}"

          ports:
            - containerPort: {{ .Values.addTask.port }}

          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: todoapp-db-secret
                  key: DB_CONNECTION_STRING

          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: todoapp-keyvault