apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: todoapp-keyvault
  namespace: default

spec:
  provider: azure

  parameters:
    clientID: "966983ef-8b54-4607-adad-fd7c088692d5"
    keyvaultName: "kubernet-kv"
    tenantId: "a7dd8b02-fc7e-452c-9b2c-c53db150afd2"

    objects: |
      array:
        - |
          objectName: DB-CONNECTION-STRING
          objectType: secret
          objectVersion: ""

  secretObjects:
    - secretName: todoapp-db-secret
      type: Opaque
      data:
        - objectName: DB-CONNECTION-STRING
          key: DB_CONNECTION_STRING